### ISSUE TITLE
Guardian DB 0.7.0 fails to compile using Elixir 1.4

### ISSUE THREAD

**Issue by st23am** [ueberauth/guardian_db#43]
It looks like a new release needs to be tagged because the fixes appear to be in master but, currently when trying to compile guardian_db as a dependency in a project I get compilation error.

```
  mix deps.compile
==> base64url (compile)
  Compiled src/base64url.erl
  warning: variable "erlc_options" does not exist and is being expanded to
  "erlc_options()", please use parentheses to remove the ambiguity or
  change the variable name
  /Users/st23am/src/elixir/test_guardian_db/deps/jose/mix.exs:8

  warning: variable "deps" does not exist and is being expanded to
  "deps()", please use parentheses to remove the ambiguity or change the
  variable name
  /Users/st23am/src/elixir/test_guardian_db/deps/jose/mix.exs:11

  warning: variable "description" does not exist and is being expanded
  to "description()", please use parentheses to remove the ambiguity
  or change the variable name
  /Users/st23am/src/elixir/test_guardian_db/deps/jose/mix.exs:19

  warning: variable "package" does not exist and is being expanded
  to "package()", please use parentheses to remove the ambiguity or
  change the variable name
  /Users/st23am/src/elixir/test_guardian_db/deps/jose/mix.exs:20

  ==> jose
  Compiling 87 files (.erl)
Compiling 8 files (.ex)
  warning: HashDict.size/1 is deprecated, use maps and the Map
  module instead
  lib/jose/poison/lexical_encoder.ex:199



  README.md
  Generated jose app
==> poolboy (compile)
  Compiled src/poolboy_worker.erl
  Compiled src/poolboy_sup.erl
  Compiled src/poolboy.erl
  ==> decimal
Compiling 1 file (.ex)
  Generated decimal app
  ==> poison
Compiling 4 files (.ex)
  warning: HashDict.size/1 is deprecated, use maps and the Map
  module instead
  lib/poison/encoder.ex:283

  Generated poison app
  ==> ecto
Compiling 68 files (.ex)
  warning: behaviour DBConnection is undefined
  lib/ecto/adapters/sql/sandbox.ex:284

  warning: behaviour DBConnection.Pool is undefined
  lib/ecto/adapters/sql/sandbox.ex:356

  Generated ecto app
  ==> uuid
Compiling 1 file (.ex)
  Generated uuid app
  ==> mime
Compiling 1 file (.ex)
  Generated mime app
  ==> plug
Compiling 44 files (.ex)
  Generated plug app
  ==> guardian
Compiling 21 files (.ex)

  == Compilation error on file lib/guardian.ex ==
  ** (RuntimeError) Guardian is not configured
lib/guardian.ex:26: (module)
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

  could not compile dependency :guardian, "mix
  compile" failed. You can recompile this
  dependency with "mix deps.compile guardian",
  update it with "mix deps.update guardian" or
  clean it with "mix deps.clean guardian"
```

Here is a repo you can use to reproduce the error: https://github.com/st23am/test_guardian_db_compile

**Comment by st23am** [comment]
Withdrawing this issue as I was missing configuration for adding the Repo that GuardianDb needs to use. My bad.
