### PR TITLE
Update ecto version [updated]

### LINKED ISSUE #93: guardian_db fails to compile with Ecto 3 rc (undefined function migrations_path/1)
See https://github.com/elixir-ecto/ecto/issues/2763

```
== Compilation error in file lib/mix/tasks/guardian_db.gen.migration.ex ==
** (CompileError) lib/mix/tasks/guardian_db.gen.migration.ex:21: undefined function migrations_path/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
```

I'm in the midst of updating a Phoenix app to use Ecto 3 (and ecto_sql), but ran into this compile failure when updating guardian_db from 0.8 to 1.1. 

https://github.com/ueberauth/guardian_db/blob/master/lib/mix/tasks/guardian_db.gen.migration.ex#L21

### PR DESCRIPTION
**Pull request by nathany**
This amends #98 to use Ecto 3.0 final.

fixes #93

### CODE REVIEW

**Comment by nathany** [comment]
I'm looking into the warning and test failure now. I didn't see the test failure locally.

update: Fixed and passing.

**Comment by nathany** [comment]
Thanks @yordis. Are you planning to do the 2.0.0 release?

**Comment by yordis** [comment]
@nathany waiting for a feedback from the other members and then we will do it.

**Comment by tcitworld** [comment]
Hi, any news on this ? :)
